# Generated by Django 3.1.4 on 2021-02-08 07:26

from django.db import migrations, models
import store.validators


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20210206_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookrelation',
            name='discount',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[store.validators.validate_percent_field]),
        ),
    ]
