# Generated by Django 3.1.4 on 2021-02-09 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20210210_0035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbookrelation',
            name='discount',
        ),
    ]
